<a href="https://colab.research.google.com/github/jyoti-kumbhar/Data-Science/blob/main/prac3a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Handling Numerical Data

In [66]:
# Rescaling a feature
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
df=pd.read_csv('/content/Financial_Statements.csv')

In [49]:
df.head()

Year Company  Category  Market Cap(in B USD)   Revenue  Gross Profit  \
0  2022     AAPL       IT               2066.94  394328.0      170782.0   
1  2021     AAPL       IT               2913.28  365817.0      152836.0   
2  2020     AAPL       IT               2255.97  274515.0      104956.0   
3  2019     AAPL       IT               1304.76  260174.0       98392.0   
4  2018     AAPL       IT                748.54  265595.0      101839.0   

   Net Income  Earning Per Share    EBITDA  Share Holder Equity  ...  \
0     99803.0               6.11  130541.0              50672.0  ...   
1     94680.0               5.61  120233.0              63090.0  ...   
2     57411.0               3.28   77344.0              65339.0  ...   
3     55256.0               2.97   76477.0              90488.0  ...   
4     59531.0               2.98   81801.0             107147.0  ...   

   Current Ratio  Debt/Equity Ratio       ROE      ROA      ROI  \
0         0.8794             2.3695  196.9589  28.2924  66.6994   
1         1.0746             1.9768  150.0713  26.9742  54.9839   
2         1.3636             1.7208   87.8664  17.7256  35.0054   
3         1.5401             1.1940   61.0645  16.3230  30.3113   
4         1.1329             1.0685   55.5601  16.2775  29.6348   

   Net Profit Margin  Free Cash Flow per Share  Return on Tangible Equity  \
0            25.3096                    1.3146                   196.9589   
1            25.8818                    1.3261                   150.0713   
2            20.9136                    1.0183                    87.8664   
3            21.2381                   -0.0388                    61.0645   
4            22.4142                    0.7414                    55.5601   

   Number of Employees  Inflation Rate(in US)  
0               164000                 8.0028  
1               154000                 4.6979  
2               147000                 1.2336  
3               137000                 1.8122  
4               132000                 2.4426  

[5 rows x 23 columns]

In [50]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Company '] = le.fit_transform(df['Company '])
df['Category'] = le.fit_transform(df['Category'])
df.tail(5)

Year  Company   Category  Market Cap(in B USD)  Revenue  Gross Profit  \
156  2013         2         7                182.54  74452.0       20271.0   
157  2012         2         7                113.63  61093.0       15122.0   
158  2011         2         7                 78.72  48077.0       10789.0   
159  2010         2         7                 80.79  34204.0        7643.0   
160  2009         2         7                 58.24  24509.0        5531.0   

     Net Income  Earning Per Share  EBITDA  Share Holder Equity  ...  \
156       274.0             0.0295  3998.0               9746.0  ...   
157       -39.0            -0.0045  2835.0               8192.0  ...   
158       631.0             0.0685  1945.0               7757.0  ...   
159      1152.0             0.1265  1974.0               6864.0  ...   
160       902.0             0.1020  1507.0               5257.0  ...   

     Current Ratio  Debt/Equity Ratio      ROE     ROA      ROI  \
156         1.0716             0.3274   2.8114  0.6823   2.1180   
157         1.1207             0.3765  -0.4761 -0.1198  -0.3459   
158         1.1741             0.0329   8.1346  2.4962   7.8757   
159         1.3254             0.2274  16.7832  6.1286  13.6736   
160         1.3304             0.2007  17.1581  6.5301  17.1581   

     Net Profit Margin  Free Cash Flow per Share  Return on Tangible Equity  \
156             0.3680                    0.1748                     3.8641   
157            -0.0638                   -0.1833                    -0.6915   
158             1.3125                   -0.0490                    10.8756   
159             3.3680                   -0.0544                    20.8885   
160             3.6803                    0.3303                    22.4211   

     Number of Employees  Inflation Rate(in US)  
156               117300                 1.4648  
157                88400                 2.0693  
158                56200                 3.1568  
159                33700                 1.6400  
160                24300                -0.3555  

[5 rows x 23 columns]

In [51]:
# create scaler
minmax_scaler = preprocessing. MinMaxScaler (feature_range=(0,1))
# scale feature
scaled_feature = minmax_scaler.fit_transform(df)
scaled_feature

array([[0.92857143, 0.        , 0.75      , ..., 0.42875308, 0.09895294,
        1.        ],
       [0.85714286, 0.        , 0.75      , ..., 0.40198924, 0.092713  ,
        0.60459663],
       [0.78571429, 0.        , 0.75      , ..., 0.36648216, 0.08834504,
        0.19012239],
       ...,
       [0.14285714, 0.18181818, 0.875     , ..., 0.32253516, 0.03168641,
        0.42021703],
       [0.07142857, 0.18181818, 0.875     , ..., 0.32825061, 0.01764654,
        0.23874472],
       [0.        , 0.18181818, 0.875     , ..., 0.32912543, 0.011781  ,
        0.        ]])

In [58]:
#deleteing missing rows
df = df.dropna()

In [59]:
# Standardizing a Feature
scaler = preprocessing.StandardScaler()
# transform the feature
standardized = scaler.fit_transform(df)
standardized

array([[ 1.57641526e+00, -1.57559791e+00,  7.36911444e-01, ...,
         1.56955687e+00,  7.82667630e-02,  2.94487993e+00],
       [ 1.32937663e+00, -1.57559791e+00,  7.36911444e-01, ...,
         1.14321204e+00,  3.34641418e-02,  1.25745257e+00],
       [ 1.08233800e+00, -1.57559791e+00,  7.36911444e-01, ...,
         5.77588351e-01,  2.10230700e-03, -5.11361808e-01],
       ...,
       [-1.14100967e+00, -9.71775955e-01,  1.13524195e+00, ...,
        -1.22482232e-01, -4.04705493e-01,  4.70592354e-01],
       [-1.38804830e+00, -9.71775955e-01,  1.13524195e+00, ...,
        -3.14358114e-02, -5.05511391e-01, -3.03860679e-01],
       [-1.63508693e+00, -9.71775955e-01,  1.13524195e+00, ...,
        -1.75000142e-02, -5.47625855e-01, -1.32273003e+00]])

In [60]:
print("Mean {}".format(round(standardized.mean())))
print("Standard Deviation: {}".format(standardized.std()))

Mean 0
Standard Deviation: 1.0


In [61]:
# using robust scaler
robust_scaler = preprocessing.RobustScaler()
robust_scaler.fit_transform(df)

array([[ 0.85714286, -0.83333333,  0.25      , ...,  5.66534019,
         0.5795235 ,  5.24182896],
       [ 0.71428571, -0.83333333,  0.25      , ...,  4.16455399,
         0.49366817,  2.44343776],
       [ 0.57142857, -0.83333333,  0.25      , ...,  2.17348907,
         0.43356944, -0.48992379],
       ...,
       [-0.71428571, -0.5       ,  0.5       , ..., -0.29084542,
        -0.345997  ,  1.13852667],
       [-0.85714286, -0.5       ,  0.5       , ...,  0.02964917,
        -0.5391715 , -0.14580864],
       [-1.        , -0.5       ,  0.5       , ...,  0.07870489,
        -0.61987551, -1.83547841]])

In [62]:
# Normalizing Observations
from sklearn.preprocessing import Normalizer
# create normalizer
normalizer = Normalizer(norm="l2")
# transform feature matrix
normalizer.transform(df)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but Normalizer was fitted without feature names
  warnings.warn(


array([[ 3.89986730e-03,  0.00000000e+00,  1.15723065e-05, ...,
         3.79878128e-04,  3.16309712e-01,  1.54351425e-05],
       [ 4.23195813e-03,  0.00000000e+00,  1.25639529e-05, ...,
         3.14248123e-04,  3.22474790e-01,  9.83736570e-06],
       [ 5.48548330e-03,  0.00000000e+00,  1.62935147e-05, ...,
         2.38608747e-04,  3.99191111e-01,  3.34994663e-06],
       ...,
       [ 2.66976945e-02,  2.65516604e-05,  9.29308114e-05, ...,
         1.44382619e-04,  7.46101657e-01,  4.19091408e-05],
       [ 4.06584275e-02,  4.04561467e-05,  1.41596514e-04, ...,
         4.22534110e-04,  6.81686072e-01,  3.31740403e-05],
       [ 5.63092421e-02,  5.60569857e-05,  1.96199450e-04, ...,
         6.28429641e-04,  6.81092376e-01, -9.96412921e-06]])

In [63]:
features_l1_norm = Normalizer(norm="l1").transform(df)
features_l1_norm

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but Normalizer was fitted without feature names
  warnings.warn(


array([[ 1.59211616e-03,  0.00000000e+00,  4.72438030e-06, ...,
         1.55084791e-04,  1.29133062e-01,  6.30137845e-06],
       [ 1.73037496e-03,  0.00000000e+00,  5.13718445e-06, ...,
         1.28490658e-04,  1.31854401e-01,  4.02232981e-06],
       [ 2.23726540e-03,  0.00000000e+00,  6.64534277e-06, ...,
         9.73170576e-05,  1.62810898e-01,  1.36628247e-06],
       ...,
       [ 1.50245171e-02,  1.49423343e-05,  5.22981699e-05, ...,
         8.12534252e-05,  4.19879593e-01,  2.35849804e-05],
       [ 2.12166301e-02,  2.11110747e-05,  7.38887614e-05, ...,
         2.20489342e-04,  3.55721608e-01,  1.73110812e-05],
       [ 2.86748044e-02,  2.85463459e-05,  9.99122106e-05, ...,
         3.20020238e-04,  3.46838102e-01, -5.07411298e-06]])

In [64]:
# Grouping Observations Using Clustering
from sklearn.cluster import KMeans
# make k-means clusterer
clusterer = KMeans(3, random_state=0)
# fit clusterer
clusterer.fit(df)
# predict groups
df['group'] = clusterer.predict(df)
df.head()

/tmp/ipython-input-3141393176.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['group'] = clusterer.predict(df)


Year  Company   Category  Market Cap(in B USD)   Revenue  Gross Profit  \
0  2022         0         6               2066.94  394328.0      170782.0   
1  2021         0         6               2913.28  365817.0      152836.0   
2  2020         0         6               2255.97  274515.0      104956.0   
3  2019         0         6               1304.76  260174.0       98392.0   
4  2018         0         6                748.54  265595.0      101839.0   

   Net Income  Earning Per Share    EBITDA  Share Holder Equity  ...  \
0     99803.0               6.11  130541.0              50672.0  ...   
1     94680.0               5.61  120233.0              63090.0  ...   
2     57411.0               3.28   77344.0              65339.0  ...   
3     55256.0               2.97   76477.0              90488.0  ...   
4     59531.0               2.98   81801.0             107147.0  ...   

   Debt/Equity Ratio       ROE      ROA      ROI  Net Profit Margin  \
0             2.3695  196.9589  28.2924  66.6994            25.3096   
1             1.9768  150.0713  26.9742  54.9839            25.8818   
2             1.7208   87.8664  17.7256  35.0054            20.9136   
3             1.1940   61.0645  16.3230  30.3113            21.2381   
4             1.0685   55.5601  16.2775  29.6348            22.4142   

   Free Cash Flow per Share  Return on Tangible Equity  Number of Employees  \
0                    1.3146                   196.9589               164000   
1                    1.3261                   150.0713               154000   
2                    1.0183                    87.8664               147000   
3                   -0.0388                    61.0645               137000   
4                    0.7414                    55.5601               132000   

   Inflation Rate(in US)  group  
0                 8.0028      0  
1                 4.6979      0  
2                 1.2336      0  
3                 1.8122      0  
4                 2.4426      0  

[5 rows x 24 columns]

In [65]:
# Deleting Observations with Missing Values
df[~np.isnan(df).any(axis=1)]

Year  Company   Category  Market Cap(in B USD)   Revenue  Gross Profit  \
0    2022         0         6               2066.94  394328.0      170782.0   
1    2021         0         6               2913.28  365817.0      152836.0   
2    2020         0         6               2255.97  274515.0      104956.0   
3    2019         0         6               1304.76  260174.0       98392.0   
4    2018         0         6                748.54  265595.0      101839.0   
..    ...       ...       ...                   ...       ...           ...   
156  2013         2         7                182.54   74452.0       20271.0   
157  2012         2         7                113.63   61093.0       15122.0   
158  2011         2         7                 78.72   48077.0       10789.0   
159  2010         2         7                 80.79   34204.0        7643.0   
160  2009         2         7                 58.24   24509.0        5531.0   

     Net Income  Earning Per Share    EBITDA  Share Holder Equity  ...  \
0       99803.0             6.1100  130541.0              50672.0  ...   
1       94680.0             5.6100  120233.0              63090.0  ...   
2       57411.0             3.2800   77344.0              65339.0  ...   
3       55256.0             2.9700   76477.0              90488.0  ...   
4       59531.0             2.9800   81801.0             107147.0  ...   
..          ...                ...       ...                  ...  ...   
156       274.0             0.0295    3998.0               9746.0  ...   
157       -39.0            -0.0045    2835.0               8192.0  ...   
158       631.0             0.0685    1945.0               7757.0  ...   
159      1152.0             0.1265    1974.0               6864.0  ...   
160       902.0             0.1020    1507.0               5257.0  ...   

     Debt/Equity Ratio       ROE      ROA      ROI  Net Profit Margin  \
0               2.3695  196.9589  28.2924  66.6994            25.3096   
1               1.9768  150.0713  26.9742  54.9839            25.8818   
2               1.7208   87.8664  17.7256  35.0054            20.9136   
3               1.1940   61.0645  16.3230  30.3113            21.2381   
4               1.0685   55.5601  16.2775  29.6348            22.4142   
..                 ...       ...      ...      ...                ...   
156             0.3274    2.8114   0.6823   2.1180             0.3680   
157             0.3765   -0.4761  -0.1198  -0.3459            -0.0638   
158             0.0329    8.1346   2.4962   7.8757             1.3125   
159             0.2274   16.7832   6.1286  13.6736             3.3680   
160             0.2007   17.1581   6.5301  17.1581             3.6803   

     Free Cash Flow per Share  Return on Tangible Equity  Number of Employees  \
0                      1.3146                   196.9589               164000   
1                      1.3261                   150.0713               154000   
2                      1.0183                    87.8664               147000   
3                     -0.0388                    61.0645               137000   
4                      0.7414                    55.5601               132000   
..                        ...                        ...                  ...   
156                    0.1748                     3.8641               117300   
157                   -0.1833                    -0.6915                88400   
158                   -0.0490                    10.8756                56200   
159                   -0.0544                    20.8885                33700   
160                    0.3303                    22.4211                24300   

     Inflation Rate(in US)  group  
0                   8.0028      0  
1                   4.6979      0  
2                   1.2336      0  
3                   1.8122      0  
4                   2.4426      0  
..                     ...    ...  
156                 1.4648      1  
157                 2.0693   

In [71]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Company '] = le.fit_transform(df['Company '])
df['Category'] = le.fit_transform(df['Category'])

In [70]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
import numpy as np

# Standardize your data
scaler = StandardScaler()
standardized_features = scaler.fit_transform(df)

# Make one NaN (example)
true_value = standardized_features[0, 0]
standardized_features[0, 0] = np.nan

# Create imputer
mean_imputer = SimpleImputer(strategy='mean')

# Impute missing values
features_mean_imputed = mean_imputer.fit_transform(standardized_features)

print("True Value:", true_value)
print("Imputed Value:", features_mean_imputed[0, 0])

True Value: 1.5830394551308353
Imputed Value: -0.009893996594587428
